const About = () => {
    return(
        <div className="about">
            <h1>About</h1>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quam, quia? Nesciunt dolores assumenda nostrum et incidunt sequi doloremque, deserunt beatae. Ab autem, incidunt mollitia eligendi facere tenetur sed eius dolore nemo optio ipsa sit voluptas assumenda totam labore maiores! Quidem rerum mollitia dolore natus fugiat iusto error magni repellat recusandae quo aperiam facilis nobis hic iste quam corporis, dicta soluta et esse nulla vero? Reprehenderit, deserunt optio molestiae eligendi nulla saepe corporis omnis excepturi magnam modi recusandae odio laboriosam veritatis dolorem repellat, eaque doloribus quae, repellendus aperiam! Excepturi perspiciatis id voluptates assumenda molestiae facere minus ullam enim, corporis eveniet minima deserunt iste natus maiores magnam cum dolorum libero architecto adipisci recusandae blanditiis necessitatibus consectetur quod reiciendis. Voluptate ipsam necessitatibus consequatur quia atque? Tenetur, modi recusandae tempore nihil eaque consequuntur dolorum illum, dolor, nesciunt eveniet autem at consequatur quisquam soluta necessitatibus aperiam repellat vero quia maxime voluptatum! Vero excepturi culpa inventore quam voluptatem, possimus maiores quisquam quo beatae necessitatibus accusamus incidunt est quos. Inventore recusandae vero distinctio sit ratione? Quia totam inventore consectetur voluptatem odit ab at sed consequatur voluptatibus, atque cum veritatis doloremque amet, est ipsa tempora autem eum? Cum impedit pariatur inventore ratione labore. Corporis officia voluptatem quis magni voluptates adipisci. Similique sed incidunt dolore. Accusantium accusamus optio dolores necessitatibus nihil laboriosam a praesentium fuga assumenda quas autem, doloremque voluptatem unde officia, illum voluptates? Dolore ab nulla rem, illum totam voluptatem, debitis qui sapiente quisquam, amet itaque libero dolores adipisci soluta doloribus pariatur cum? Quae et ipsa dolorum. Dignissimos facere magni, eum, mollitia ducimus nihil, doloremque adipisci assumenda quisquam ab vero sit! Corrupti vitae vel deleniti reiciendis, possimus reprehenderit ea illo commodi in sequi atque asperiores eos neque quisquam a. Itaque, tempore aperiam illum officiis voluptas distinctio iure modi ducimus blanditiis. Quos cum animi inventore ut fugiat magnam illum.</p>
        </div>
    )
}

export default About;